#!/usr/bin/env bash

set -e

ORIG_PATH=`pwd`
COMPONENT=$1

if [ -z "$COMPONENT" -a "${COMPONENT+xxx}" = "xxx" ]; then
  echo "Provide component name"
  exit 1;
fi

cd ../build

npm install --silent arc-tools

FULL_NAME="advanced-rest-client/$COMPONENT";
SSH="git@github.com:${FULL_NAME}.git";
WORKING_DIR="`pwd`/${COMPONENT}";

if [ -d "$WORKING_DIR" ]; then
  rm -rf $WORKING_DIR
fi

if [ ! -d "$WORKING_DIR" ]; then
  mkdir -p $WORKING_DIR
fi

function version() {
  local __version=$1
  local version=`node -pe 'JSON.parse(process.argv[1]).version' "$(cat bower.json)"`
  eval $__version="'$version'"
}

function throwError() {
  echo $1
  exit 111
}

function setMaster() {
  git checkout master
}
function setStage() {
  git checkout stage
}

git clone $SSH
cd $COMPONENT

git config --global user.email "arc@mulesoft.com"
git config --global user.name "CI Agent"

version elementVersion || throwError "Error to read element version number."
setStage
echo "Bumping version"
$ORIG_PATH/node_modules/.bin/arc bump $elementVersion || throwError "Unable to bump version"
echo "Generating docs"
$ORIG_PATH/node_modules/.bin/arc docs || throwError "Unable to generate docs"
echo "Building changelog"
$ORIG_PATH/node_modules/.bin/arc changelog || throwError "Unable to build changelog"
git add -A
echo "Commiting changes made to the stage branch"
git commit -m "[CI] Automated commit after stage build (bump, docs, changelog)." || throwError "Unable to commit changes to stage. Exiting."

echo "Stage updated, merging with master"
setMaster
# echo "checking status on master before merge"
# git status
git merge --no-ff -m "[CI] Automated merge stage->master" stage || throwError "Unable to merge changes to master. Exiting."
# echo "checking status on master after merge"
# git status
# git add -A > /dev/null
# git commit -m "[CI] Automated commit after merge stage->master" > /dev/null
# echo "checking status on master after commit"
# git status
echo "Pushing master"
git push origin master || throwError "Unable to push changes to master. Exiting."
echo "Pushing stage"
git push origin stage || {
  echo "Changes to master has been made, however error occurred when pushing changes to the stage. Please, merge stage manually from master."
  exit 0;
}
exit 0;
