#!/usr/bin/env bash

set -e

ORIG_PATH=`pwd`
COMPONENT=$1
BUILD_PATH="`pwd`/../build"

echo " "
echo "  Hello. Building release for $COMPONENT"

if [ -z "$COMPONENT" -a "${COMPONENT+xxx}" = "xxx" ]; then
  echo "  Empty component name"
  exit 1;
fi

function ensureDir() {
  if [ ! -d "$1" ]; then
    mkdir -p $1
  fi
}
function version() {
  local __version=$1
  local version=`node -pe 'JSON.parse(process.argv[1]).version' "$(cat bower.json)"`
  eval $__version="'$version'"
}
function throwError() {
  echo $1
  exit 111
}

FULL_NAME="advanced-rest-client/$COMPONENT";
SSH="git@github.com:${FULL_NAME}.git";
WORKING_DIR="${BUILD_PATH}/${COMPONENT}";

ensureDir $WORKING_DIR
cd $WORKING_DIR

if [ -d "$WORKING_DIR/.git/" ]; then
  git fetch --all
  git reset --hard origin/master
  git checkout master 2> /dev/null;
else
  cd ..
  git clone $SSH
  cd $COMPONENT
fi

version elementVersion || throwError "  Error to read element version number."

if git rev-parse $elementVersion >/dev/null 2>&1
then
    echo "  Tag $elementVersion already exists."
    exit 0;
fi
echo "  Tagging version..."
git tag -s -a $elementVersion -m "Created Tag for version: $elementVersion" || throwError "  Error: Tag $elementVersion already exists."
echo "  Pushing tags..."
git push origin master --tags
# echo "  Installing conventional-github-releaser..."
# npm install --silent conventional-github-releaser
echo "  Creating the release..."
./node_modules/.bin/conventional-github-releaser -p eslint --token $GITHUB_TOKEN

echo "  The element has been released."
exit 0;
