#!/usr/bin/env bash

set -e

cd ../build

echo " "
echo "  Hello. I'm about to update the catalog."

UPDATE_DEPS=0
if [ ! -d ./arc-element-catalog ]; then
  git clone git@github.com:advanced-rest-client/arc-element-catalog.git;
  cd arc-element-catalog;
else
  cd arc-element-catalog
  git fetch --all
  git reset --hard origin/master
  git checkout master 2> /dev/null;
  UPDATE_DEPS=1
fi
if [ $UPDATE_DEPS == 0 ]; then
  echo "  Installing node..."
  npm install --silent
  echo "  Installing bower..."
  bower install --silent -F
else
  echo "  Updating node..."
  npm update --dev --silent
  echo "  Updating bower..."
  bower update --save --save-dev --silent -F
fi

echo "  Building the catalog..."
gulp
echo "  Deploying the catalog... "
firebase deploy --token "$FIREBASE_TOKEN" --project arc-element-catalog --non-interactive
exit 0
