#!/usr/bin/env bash

set -e

COMPONENT=$1

if [ -z "$COMPONENT" -a "${COMPONENT+xxx}" = "xxx" ]; then
  echo "Empty component name"
  exit 1;
fi


function ensureDir() {
  if [ ! -d "$1" ]; then
    mkdir -p $1
  fi
}

function version() {
  local __version=$1
  local version=`node -pe 'JSON.parse(process.argv[1]).version' "$(cat bower.json)"`
  eval $__version="'$version'"
}

function throwError() {
  echo $1
  exit 111
}

BUILD_PATH="`pwd`/../build"
cd $BUILD_PATH
echo " "
echo "  Hello. Updatnig structure for $COMPONENT"

echo "  Instaling build tools..."
npm install --silent arc-tools

echo "  Updating component..."
./node_modules/.bin/arc clone $COMPONENT

echo "  Structuring element..."
./node_modules/.bin/arc structure --release $COMPONENT || throwError "Unable to update the structure element"

echo " Done."
exit 0
